### PR TITLE
Enforce frequency

### PR DESCRIPTION
**Pull request by rkdarst**
Hi,

This is the "low frequency sensors" of #160.

Still being tested!  Don't merge yet, just for comments.  Comments and improvements always welcome.

### CODE REVIEW

**Comment by rkdarst** [comment]
@AnaTomomi and I have tested for a few days and it seems to work... she reports ~1.5h extended battery time when running accelerometer with some unknown parameters.

**Comment by denzilferreira** [comment]
Nice! IO has a huge hit on battery life.

**Comment by rkdarst** [comment]
Good!  I didn't think through the optimization very much.  There could be a minimum time and maximum time for the DB commits, too.  Do you think anything like this won't break your work, and if so, what delays?

I just got the idea of very long commit intervals, where syncs send a message "commit now" so that there is not much risk of long commit interval + long sync interval playing badly together.

**Comment by denzilferreira** [comment]
Yes, that will make coordinating sensors difficult, especially if we are doing sensor fusion.

**Comment by rkdarst** [comment]
I've rebased this to current development and it's seemed to work over the last week.  Is this useful, and would you like any other changes before including?

**Comment by rkdarst** [comment]
Also, should this be on by default?

**Comment by denzilferreira** [comment]
Not on by default. Have it as a setting adjustable on the client (enforce_sampling_rate), applicable to all high frequency sensors. thanks!

**Comment by rkdarst** [comment]
It should be off by default for all sensors, as I always do.  If it isn't somewhere, let me know.

I added UI options already.  I did it per-sensor, not globally (I assumed you preferred it this way).  Is this good enough?

**Comment by rkdarst** [comment]
Getting back to this... rebased to development.  Seems to work for me still.

The one blocker was UI options.  It has separate options for every sensor.  I got a bit annoyed at having to turn them all on separately, so I'm thinking to make a global setting now.  Can you think of any reason to keep the per-sensor settings?

**Comment by denzilferreira** [comment]
Flexibility. You may want to enforce only for some, but not others.

**Comment by rkdarst** [comment]
I've updated the PR with the global option, and another serious problem.  In the future I would like to test the practical effects of this on more phone models.

**Comment by denzilferreira** [comment]
@rkdarst what is the serious problem? I was looking at the code changes and they seemed ok.

**Comment by rkdarst** [comment]
Basically it wasn't updating timestamps properly, so it was letting
all data go through, I think.  I fixed it and rebased to clean up the
commits, so the problem isn't visible anymore.  I'm really obsessive
about clean commits before merging.

**Comment by denzilferreira** [comment]
That's good 👍 

So it's working OK now? Can I safely merge this?

**Comment by rkdarst** [comment]
As far as I know there are no current problems.  Of course I've made
many mistake in the past.  We've been using it for quite a while now.

**Pull request merged**
